//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBL_VersionReleaseFormAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugReportTable
    {
        public int ID { get; set; }
        public int Table_BugId { get; set; }
        public string BugReportId { get; set; }
        public string Table_BugTitle { get; set; }
        public string Table_BugDescription { get; set; }
        public string Table_ReportingDate { get; set; }
        public string Table_Severirty { get; set; }
        public string Table_DevStatus { get; set; }
        public string Table_QAStatus { get; set; }
    }
}
