//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBL_VersionReleaseFormAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugReport
    {
        public int ID { get; set; }
        public Nullable<int> FormId { get; set; }
        public string Bug_Report_ID { get; set; }
        public string BR_Holder { get; set; }
        public string Date { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string Version_Release { get; set; }
        public string TestingType { get; set; }
        public string TesterName { get; set; }
        public string TestingCycle { get; set; }
        public string Reviewer { get; set; }
        public string Data_Severity { get; set; }
        public string Data_Priority { get; set; }
        public string Data_QAStatus { get; set; }
        public string Data_DevelopmentStatus { get; set; }
    }
}
