//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBL_VersionReleaseFormAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public int FormIdd { get; set; }
        public string FormHolder { get; set; }
        public string ProjectName { get; set; }
        public string VersionNo { get; set; }
        public string VersionDescription { get; set; }
        public string VersionDate { get; set; }
        public string Type { get; set; }
    }
}
