//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBL_VersionReleaseFormAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormData
    {
        public int FormId { get; set; }
        public bool SFLandRFLisAttached { get; set; }
        public bool CpybaselineProvided { get; set; }
        public string VSSLabel { get; set; }
        public bool RelFoldersLabeled { get; set; }
        public string RelFilesLocation { get; set; }
        public bool RelFilesPlaced { get; set; }
        public bool UnitTestingDone { get; set; }
        public bool CodingStdFollowed { get; set; }
        public bool PeerReview { get; set; }
        public string PeerReviewValues { get; set; }
        public string LeadDeveloperName_SDD { get; set; }
        public bool LeadDeveloperSign_SDD { get; set; }
        public string UnitInchargeName_SDD { get; set; }
        public bool UnitInchargeSign_SDD { get; set; }
        public string DepartmentHeadName_SDD { get; set; }
        public bool DepartmentHeadSign_SDD { get; set; }
        public string DateAndTime_SDD { get; set; }
        public bool C_CCA_ChecklistChecked_SDD { get; set; }
        public string C_CCA_RelFilesMovedToLoc_SDD { get; set; }
        public bool C_CCA_RelFilesMovedOrNot_SDD { get; set; }
        public string C_CCA_DateAndTime_SDD { get; set; }
        public bool C_CCA_Sign_SDD { get; set; }
        public bool DiscoveredBugsReported { get; set; }
        public string DiscoveredBugsReportedRepNo { get; set; }
        public bool QATeamSatisfied { get; set; }
        public string SWStabilityComment_QA { get; set; }
        public string LeadName_QA { get; set; }
        public bool LeadSign_QA { get; set; }
        public string ManagerName_QA { get; set; }
        public bool ManagerSign_QA { get; set; }
        public string DateAndTime_QA { get; set; }
        public bool C_CCA_ChecklistChecked_QA { get; set; }
        public string C_CCA_RelFilesMovedToLoc_QA { get; set; }
        public bool C_CCA_RelFilesMovedOrNot_QA { get; set; }
        public string C_CCA_DateAndTime_QA { get; set; }
        public bool C_CCA_Sign_QA { get; set; }
        public bool FilesCopiedToDestination_Deployment { get; set; }
        public bool FilesExecuted_Deployment { get; set; }
        public string Production_Deployment { get; set; }
        public string FailoverSite_Deployment { get; set; }
        public string DeployedByName_Deployment { get; set; }
        public bool DeployedBySign_Deployment { get; set; }
        public string UnitInchargeName_Deployment { get; set; }
        public bool UnitInchargeSign_Deployment { get; set; }
        public bool DepartmentHead_Deployment_Sign { get; set; }
        public string DepartmentHead_Deployment_Name { get; set; }
        public string DateAndTime_Deployment { get; set; }
        public bool C_CCA_ChecklistConfirmed_Deployment { get; set; }
        public string C_CCA_DateAndTime_Deployment { get; set; }
        public bool C_CCA_Sign_Deployment { get; set; }
        public string FormHolder { get; set; }
        public string ProjectName { get; set; }
        public string VersionNo { get; set; }
        public string VersionDescription { get; set; }
        public string VersionDate { get; set; }
        public string Type { get; set; }
        public string ProjectId { get; set; }
    }
}
