//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBL_VersionReleaseFormAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string Version { get; set; }
        public string ProjectDescription { get; set; }
        public string Manager_SDD { get; set; }
        public string UnitIncharge_SDD { get; set; }
        public string LeadDeveloper_SDD { get; set; }
        public string Manager_QA { get; set; }
        public string UnitIncharge_QA { get; set; }
        public string Manager_Operations { get; set; }
        public string UnitIncharge_Operations_ { get; set; }
    }
}
