//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBL_VersionReleaseFormAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareFeatureList
    {
        public int ID { get; set; }
        public int FormId { get; set; }
        public int S_No_ { get; set; }
        public string ImplemetedFeatures { get; set; }
        public byte[] LeadDeveloperSign { get; set; }
        public byte[] UnitInchargeSign { get; set; }
        public byte[] DepartmentHeadSign { get; set; }
    }
}
