//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBL_VersionReleaseFormAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAT_Team
    {
        public int Id { get; set; }
        public int UATFormId { get; set; }
        public string PPNo { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
    }
}
