//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBL_VersionReleaseFormAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UATForm
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string Functionalities { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Department { get; set; }
        public string SVP_Name { get; set; }
        public string SVP_PPNo { get; set; }
        public string SVP_Designation { get; set; }
        public string Holder_PPNo { get; set; }
    }
}
