//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZTBL_VersionReleaseFormAutomation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        [Required]
        [MinLength(5)]
        [MaxLength(5)]
        public string PPNumber { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
        public string Designation { get; set; }
        public string UserType { get; set; }
        public string PasswordSalt { get; set; }
        public string LastLogin { get; set; }
        public string UserRole { get; set; }
        public string Boss { get; set; }
        public bool rememberMe { get; set; }
        public String submitNote { get; set; }
    }
}
